#!/bin/bash
source /vagrant/provision/scripts/00-env.sh

echo "----------------------------------------"
echo "Playerbots GM Commands (Living World Mode)"
echo "----------------------------------------"
echo ""
echo "Bot Management:"
echo "  .playerbot add <class>      -> Add a personal bot"
echo "  .playerbot remove all        -> Remove all your bots"
echo "  .playerbot stats             -> Detailed info"
echo ""
echo "Orders (Behavior):"
echo "  .playerbot follow            -> Follow the master"
echo "  .playerbot grind             -> Autonomous XP / farming"
echo "  .playerbot quest             -> Do quests"
echo "  .playerbot dungeon           -> Dungeon mode (auto tank/heal)"
echo "  .playerbot raid              -> Mode Raid"
echo "  .playerbot stay              -> Stay in place"
echo ""
echo "World Population:"
echo "  .rndbot login                -> Add random bots"
echo "  .rndbot logout               -> Remove random bots"
echo ""
echo "Useful GM commands:"
echo "  .gm on / .gm off             -> God mode"
echo "  .tele dalaran                -> Teleport"
echo "  .lookup item <name>           -> Search for an item"
echo "  .additem <id>                -> Give yourself an item"
echo ""
echo "Tip:"
echo "  Target a bot and type .playerbot control to play it!"
echo ""
