#!/bin/bash
source /vagrant/provision/scripts/00-env.sh

echo "----------------------------------------"
echo "Commandes GM Playerbots (Mode Living World)"
echo "----------------------------------------"
echo ""
echo "Gestion Bots:"
echo "  .playerbot add <classe>      -> Ajouter un bot perso"
echo "  .playerbot remove all        -> Supprimer tous vos bots"
echo "  .playerbot stats             -> Infos detaillees"
echo ""
echo "Ordres (Comportement):"
echo "  .playerbot follow            -> Suivre le maitre"
echo "  .playerbot grind             -> XP / Farm autonome"
echo "  .playerbot quest             -> Faire des quetes"
echo "  .playerbot dungeon           -> Mode Donjon (tank/heal auto)"
echo "  .playerbot raid              -> Mode Raid"
echo "  .playerbot stay              -> Rester sur place"
echo ""
echo "Population Monde:"
echo "  .rndbot login                -> Ajouter des bots aleatoires"
echo "  .rndbot logout               -> Retirer des bots aleatoires"
echo ""
echo "Commandes GM utiles:"
echo "  .gm on / .gm off             -> Mode Dieu"
echo "  .tele dalaran                -> Teleportation"
echo "  .lookup item <nom>           -> Chercher un objet"
echo "  .additem <id>                -> Se donner un objet"
echo ""
echo "Astuce:"
echo "  Ciblez un bot et tapez .playerbot control pour le jouer!"
echo ""
